spring:
  application:
    name: shea-ai-agent
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus
  profiles:
    active: local
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.100.104:3306/shea_ai_agent?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.shea.ai.sheaaiagent.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.shea.ai.sheaaiagent.model